export const CONFIG = {
  canvas: { w: 1024, h: 768, scale: 1 },
  speed: 140,
  torchRadius: 180,
  shadowPenalty: 0.25,

  // cellule de collision plus large pour lisser la texture brique
  collisionCell: 1,
  // decallage leger : on s'aligne exactement sur les coordonnées du map.json
  collisionOffset: { x: 13, y: -8 },
  // on élargit légèrement les collisions pour éviter de traverser les murs
  collisionInflation: 1.15,

  playerAttackRadius: 25.3,
  playerAttackDuration: 0.28,
  playerMouseDeadzone: 18,
  dashDistance: 140,
  dashCooldown: 1.05,
  dashStaminaCost: 18,
  dashDuration: 0.25,
  comboDoubleTapWindow: 0.28,
  heavyHoldTime: 0.45,
  lightAttackDamage: 15,
  heavyAttackDamage: 32,
  comboAttackDamage: 22,
  comboWindowDuration: 0.35,

  kael: {
    hp: 320,
    speed: 120,
    preferredDistance: 140,
    attackRange: 180,
    attackCooldown: 2.8,
    attackWindup: 0.85,
    dashDuration: 0.4,
    dashSpeed: 360,
    dashDamage: 42,
    knockback: 32,
    knockbackResistance: 0.35,
    orbCooldown: 7.5,
    orbCount: 4,
    orbLifetime: 4,
    orbOrbitRadius: 110,
    orbSpinSpeed: 2.4,
    orbLaunchSpeed: 240,
    orbDamage: 28,
    fissureCooldown: 9,
    fissureWindup: 1,
    fissureLength: 320,
    fissureSpeed: 320,
    fissureWidth: 42,
    fissureDamage: 36,
    phaseTwo: {
      hpMultiplier: 1.5,
      sigilDamage: 38,
      cloneDamage: 44,
      beamDamage: 52,
    },
    phaseThree: {
      hpMultiplier: 2.2,
      dragonScale: 0.55,
      meteorDamage: 65,
      infernoDamage: 58,
      shockwaveDamage: 54,
      stormDamage: 62,
    },
  },

  // Sprint / endurance
  staminaMax: 100,
  sprintMult: 1.8,
  staminaDrain: 28,
  staminaRegen: 18,
};
