export const State = {
  started: false,
  heroSrc: null,
  mode: "LIGHT",            // LIGHT | SHADOW
  time: 0,
  dt: 0,
  last: 0,

  player: null,
  kael: null,
  boss: null,
  bossCheckpoint: null,
  bossRetryShown: false,
  paused: false,
  sounds: {},
  gameOverSoundPlayed: false,
  pickups: [],
  statusMessage: "",
  statusTimer: 0,
  princess: { x: 512, y: 240, freed: false },
  map: null,
  pointer: { x: 0, y: 0 },
  attackInput: null,
  dialogue: null,
  inventory: null,
  touchControls: null,
  isMobile: false,
  puzzleOrbs: [],
  showCollisionDebug: true,
  orbPromptOpen: false,
  princessHint: null,
  bossMusicPending: false,
  activeBossTrack: null,
  questAnnouncement: null,
  questPromptCooldown: 0,
  floatingTexts: [],
  projectiles: [],
  lastAim: { x: 1, y: 0 },
  flags: {
    foundShrine: 0,
    betrayalHappened: false,
    princessQuestAccepted: false,
    preQuestBoundaryWarned: false,
    enemyWarningSpoken: false,
    kaelDown: false,
    kaelAggro: false,
    questCompletedShown: false,
    kaelMet: false,
    kaelDefeated: false,
    kaelPhaseTwoStarted: false,
    kaelPhaseTwoDefeated: false,
    kaelPhaseThreeStarted: false,
    kaelPhaseThreeDefeated: false,
    princessEscapeOffered: false,
    endingPending: false,
    visited: new Set(),
    princessUnlocked: false,
  }
};
